name: Deploy
on:
  workflow_run:
    workflows: ["Synth"]
    branches: [main]
    types: 
      - completed
    
permissions:
  id-token: write
  contents: read
  
jobs:
  # test_workflow:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event.workflow_run.conclusion == 'success' }}
  #   steps: 
  #     - run: echo "success"
  Deploy:
    # needs: test_workflow
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependiencies
        run: yarn

      - name: Synth stack
        run: yarn cdk synth --all --require-approval never
