name: DMS Stack
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the Env'
        required: true
        default: ''
        type: choice
        options:
        - dev
        - stage
        - prod
      Account:
        description: 'Choose the Account'
        required: true
        default: ''
        type: choice
        options:
        - BRANDS
env:
  AWS_OIDC_ROLE_ARN: ${{ github.event.inputs.Account }}_AWS_OIDC_ROLE_ARN
permissions:
  id-token: write
  contents: read
  
jobs:
  DeployStacks:

    environment:
      name: ${{ github.event.inputs.environment }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          badges-directory: build/reports/jacoco/test/html/badges
          
      - name: Publish coverage report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/reports/jacoco/test/html
          

      - name: Install Dependiencies
        run: yarn

      - name: Synth stack
        run: yarn cdk synth --all --require-approval never
