on: push

env:
  ROLE_NAME: ${{ secrets.ROLE_NAME }}


jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::128680359488:role/ExampleGithubRole
          aws-region: us-east-1
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::209185650497:role/ExampleGithubRole
          aws-region: us-east-1
      - name: Install dependencies
        run: yarn
      - name: Synth stack
        run: yarn cdk synth
      - name: cdk bootstrap
        run: cdk bootstrap
      - name: Deploy stack
        run: yarn cdk deploy --all --require-approval never
