name: DMS Stack
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the Env'
        required: true
        default: ''
        type: choice
        options:
        - dev
        - stage
        - prod
      Account:
        description: 'Choose the Account'
        required: true
        default: ''
        type: choice
        options:
        - BRANDS   
permissions:
  id-token: write
  contents: read
  
jobs:
  DeployStacks:

    environment:
      name: ${{ github.event.inputs.environment }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependiencies
        run: yarn


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam:::role/ExampleGithubRole
          aws-region: es-east-1

      - name: Deploy stack
        run: yarn cdk deploy --all --require-approval never
